version: '3.8'
services:
  api_client:
    build:
      context: ./api_client
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./api_client:/api_client
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=portal
      - MYSQL_USER=tron
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=movie
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data
      - ./db/dump:/docker-entrypoint-initdb.d
      # To just mount the dump directory
      # - ./dump:/dump
volumes:
  db_data:
